/+
 +  Protocol copyright:
 +  Copyright © 2022 Kenny Levinsen
 +
 +  Permission is hereby granted, free of charge, to any person obtaining a
 +  copy of this software and associated documentation files (the "Software"),
 +  to deal in the Software without restriction, including without limitation
 +  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 +  and/or sell copies of the Software, and to permit persons to whom the
 +  Software is furnished to do so, subject to the following conditions:
 +
 +  The above copyright notice and this permission notice (including the next
 +  paragraph) shall be included in all copies or substantial portions of the
 +  Software.
 +
 +  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 +  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 +  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 +  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 +  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 +  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 +  DEALINGS IN THE SOFTWARE.
 +/
/+
 +  D bindings copyright:
 +  Copyright © 2015 Rémi Thebault
 +/
/+
 +      File generated by wayland-scanner-d:
 +  /home/eirikr/.dub/packages/wayland-scanner-d/1.0.0/wayland-scanner-d/wayland-scanner-d -i /usr/share/wayland-protocols/staging/fractional-scale/fractional-scale-v1.xml -m pured.platform.wayland.fractional_scale.protocol --client --protocol -o /home/eirikr/Github/tilix/pured/platform/wayland/fractional_scale/protocol.d -x wayland.client.core -x wayland.client.ifaces
 +      Do not edit!
 +/
module pured.platform.wayland.fractional_scale.protocol;

import wayland.client.util;
import wayland.client.opaque_types;
import wayland.client.core;
import wayland.client.ifaces;
import wayland.client.protocol;
import pured.platform.wayland.fractional_scale.ifaces;

extern (C) {

    struct wp_fractional_scale_manager_v1;
    struct wp_fractional_scale_v1;

    /++
     +  WP_FRACTIONAL_SCALE_MANAGER_V1_ERROR_FRACTIONAL_SCALE_EXISTS: the surface already has a fractional_scale object associated
     +
     +/
    enum uint WP_FRACTIONAL_SCALE_MANAGER_V1_ERROR_FRACTIONAL_SCALE_EXISTS = 0;

    enum uint WP_FRACTIONAL_SCALE_MANAGER_V1_DESTROY = 0;
    enum uint WP_FRACTIONAL_SCALE_MANAGER_V1_GET_FRACTIONAL_SCALE = 1;

    extern (D) void
    wp_fractional_scale_manager_v1_set_user_data(wp_fractional_scale_manager_v1 *wp_fractional_scale_manager_v1, void *user_data)
    {
        wl_proxy_set_user_data(cast(wl_proxy*) wp_fractional_scale_manager_v1, user_data);
    }

    extern (D) void *
    wp_fractional_scale_manager_v1_get_user_data(wp_fractional_scale_manager_v1 *wp_fractional_scale_manager_v1)
    {
        return wl_proxy_get_user_data(cast(wl_proxy*) wp_fractional_scale_manager_v1);
    }

    /++
     +  unbind the fractional surface scale interface
     +
     +  Informs the server that the client will not be using this protocol
     +  object anymore. This does not affect any other objects,
     +  wp_fractional_scale_v1 objects included.
     +/
    extern (D) void
    wp_fractional_scale_manager_v1_destroy(wp_fractional_scale_manager_v1 *wp_fractional_scale_manager_v1_)
    {
        wl_proxy_marshal(cast(wl_proxy*) wp_fractional_scale_manager_v1_,
                WP_FRACTIONAL_SCALE_MANAGER_V1_DESTROY);

        wl_proxy_destroy(cast(wl_proxy*) wp_fractional_scale_manager_v1_);
    }

    /++
     +  extend surface interface for scale information
     +
     +  Create an add-on object for the the wl_surface to let the compositor
     +  request fractional scales. If the given wl_surface already has a
     +  wp_fractional_scale_v1 object associated, the fractional_scale_exists
     +  protocol error is raised.
     +/
    extern (D) wp_fractional_scale_v1 *
    wp_fractional_scale_manager_v1_get_fractional_scale(wp_fractional_scale_manager_v1 *wp_fractional_scale_manager_v1_, wl_surface *surface)
    {
        wl_proxy *id;

        id = wl_proxy_marshal_constructor(
                cast(wl_proxy*) wp_fractional_scale_manager_v1_,
                WP_FRACTIONAL_SCALE_MANAGER_V1_GET_FRACTIONAL_SCALE, wp_fractional_scale_v1_interface, null, surface);

        return cast(wp_fractional_scale_v1 *) id;
    }

    /++
     +  fractional scale interface to a wl_surface
     +
     +  An additional interface to a wl_surface object which allows the compositor
     +  to inform the client of the preferred scale.
     +/
    struct wp_fractional_scale_v1_listener
    {
        /++
         +  notify of new preferred scale
         +
         +  Notification of a new preferred scale for this surface that the
         +  compositor suggests that the client should use.
         +
         +  The sent scale is the numerator of a fraction with a denominator of 120.
         +/
        void function (void *data,
                       wp_fractional_scale_v1 *wp_fractional_scale_v1,
                       uint scale) preferred_scale;
    }

    extern (D) int
    wp_fractional_scale_v1_add_listener(wp_fractional_scale_v1 *wp_fractional_scale_v1,
                    const(wp_fractional_scale_v1_listener) *listener, void *data)
    {
        alias Callback = extern (C) void function();

        return wl_proxy_add_listener(
                cast(wl_proxy*)wp_fractional_scale_v1,
                cast(Callback*)listener, data);
    }

    enum uint WP_FRACTIONAL_SCALE_V1_DESTROY = 0;

    extern (D) void
    wp_fractional_scale_v1_set_user_data(wp_fractional_scale_v1 *wp_fractional_scale_v1, void *user_data)
    {
        wl_proxy_set_user_data(cast(wl_proxy*) wp_fractional_scale_v1, user_data);
    }

    extern (D) void *
    wp_fractional_scale_v1_get_user_data(wp_fractional_scale_v1 *wp_fractional_scale_v1)
    {
        return wl_proxy_get_user_data(cast(wl_proxy*) wp_fractional_scale_v1);
    }

    /++
     +  remove surface scale information for surface
     +
     +  Destroy the fractional scale object. When this object is destroyed,
     +  preferred_scale events will no longer be sent.
     +/
    extern (D) void
    wp_fractional_scale_v1_destroy(wp_fractional_scale_v1 *wp_fractional_scale_v1_)
    {
        wl_proxy_marshal(cast(wl_proxy*) wp_fractional_scale_v1_,
                WP_FRACTIONAL_SCALE_V1_DESTROY);

        wl_proxy_destroy(cast(wl_proxy*) wp_fractional_scale_v1_);
    }


} // extern (C)

