/+
 +  Protocol copyright:
 +  Copyright © 2022 Kenny Levinsen
 +
 +  Permission is hereby granted, free of charge, to any person obtaining a
 +  copy of this software and associated documentation files (the "Software"),
 +  to deal in the Software without restriction, including without limitation
 +  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 +  and/or sell copies of the Software, and to permit persons to whom the
 +  Software is furnished to do so, subject to the following conditions:
 +
 +  The above copyright notice and this permission notice (including the next
 +  paragraph) shall be included in all copies or substantial portions of the
 +  Software.
 +
 +  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 +  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 +  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 +  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 +  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 +  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 +  DEALINGS IN THE SOFTWARE.
 +/
/+
 +  D bindings copyright:
 +  Copyright © 2015 Rémi Thebault
 +/
/+
 +      File generated by wayland-scanner-d:
 +  /home/eirikr/.dub/packages/wayland-scanner-d/1.0.0/wayland-scanner-d/wayland-scanner-d -i /usr/share/wayland-protocols/staging/fractional-scale/fractional-scale-v1.xml -m pured.platform.wayland.fractional_scale.priv.ifaces --client --ifaces --ifaces_priv -o /home/eirikr/Github/tilix/pured/platform/wayland/fractional_scale/priv/ifaces.d -x pured.platform.wayland.fractional_scale.protocol -x wayland.client.core
 +      Do not edit!
 +/
module pured.platform.wayland.fractional_scale.priv.ifaces;

import wayland.client.util;
import wayland.client.opaque_types;
import pured.platform.wayland.fractional_scale.protocol;
import wayland.client.core;

extern (C) {

    // Define interface symbols for static linking
    // These are protocol metadata structures
    wl_interface wp_fractional_scale_manager_v1_interface = {
        "wp_fractional_scale_manager_v1", 1, 2, null, 0, null
    };

    wl_interface wp_fractional_scale_v1_interface = {
        "wp_fractional_scale_v1", 1, 1, null, 1, null
    };

    version (Dynamic) {}

} // extern (C)

