/+
 +  Protocol copyright:
 +  Copyright © 2015, 2016 Red Hat
 +
 +  Permission is hereby granted, free of charge, to any person obtaining a
 +  copy of this software and associated documentation files (the "Software"),
 +  to deal in the Software without restriction, including without limitation
 +  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 +  and/or sell copies of the Software, and to permit persons to whom the
 +  Software is furnished to do so, subject to the following conditions:
 +
 +  The above copyright notice and this permission notice (including the next
 +  paragraph) shall be included in all copies or substantial portions of the
 +  Software.
 +
 +  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 +  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 +  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 +  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 +  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 +  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 +  DEALINGS IN THE SOFTWARE.
 +/
/+
 +  D bindings copyright:
 +  Copyright © 2015 Rémi Thebault
 +/
/+
 +      File generated by wayland-scanner-d:
 +  /home/eirikr/.dub/packages/wayland-scanner-d/1.0.0/wayland-scanner-d/wayland-scanner-d -i /usr/share/wayland-protocols/unstable/primary-selection/primary-selection-unstable-v1.xml -m pured.platform.wayland.primary_selection.priv.ifaces --client --ifaces --ifaces_priv -o /home/eirikr/Github/tilix/pured/platform/wayland/primary_selection/priv/ifaces.d -x pured.platform.wayland.primary_selection.protocol -x wayland.client.core
 +      Do not edit!
 +/
module pured.platform.wayland.primary_selection.priv.ifaces;

import wayland.client.util;
import wayland.client.opaque_types;
import wayland.client.core;
import wlpriv = wayland.client.priv.ifaces;

extern (C) {

    version (Dynamic) {}
    else {
        __gshared wl_interface zwp_primary_selection_device_manager_v1_interface;
        __gshared wl_interface zwp_primary_selection_device_v1_interface;
        __gshared wl_interface zwp_primary_selection_offer_v1_interface;
        __gshared wl_interface zwp_primary_selection_source_v1_interface;
    }

} // extern (C)

version (Dynamic) {}
else {
    private __gshared const(wl_interface)*[9] wp_primary_selection_unstable_v1_types;
    private __gshared wl_message[3] zwp_primary_selection_device_manager_v1_requests;
    private __gshared wl_message[2] zwp_primary_selection_device_v1_requests;
    private __gshared wl_message[2] zwp_primary_selection_device_v1_events;
    private __gshared wl_message[2] zwp_primary_selection_offer_v1_requests;
    private __gshared wl_message[1] zwp_primary_selection_offer_v1_events;
    private __gshared wl_message[2] zwp_primary_selection_source_v1_requests;
    private __gshared wl_message[2] zwp_primary_selection_source_v1_events;

    shared static this() {
        wp_primary_selection_unstable_v1_types = [
            null,
            null,
            &zwp_primary_selection_source_v1_interface,
            &zwp_primary_selection_device_v1_interface,
            &wlpriv.wl_seat_interface,
            &zwp_primary_selection_source_v1_interface,
            null,
            &zwp_primary_selection_offer_v1_interface,
            &zwp_primary_selection_offer_v1_interface
        ];

        zwp_primary_selection_device_manager_v1_requests[0] =
            wl_message("create_source".ptr, "n".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 2);
        zwp_primary_selection_device_manager_v1_requests[1] =
            wl_message("get_device".ptr, "no".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 3);
        zwp_primary_selection_device_manager_v1_requests[2] =
            wl_message("destroy".ptr, "".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);

        zwp_primary_selection_device_manager_v1_interface = wl_interface(
            "zwp_primary_selection_device_manager_v1".ptr, 1,
            3, zwp_primary_selection_device_manager_v1_requests.ptr,
            0, null);

        zwp_primary_selection_device_v1_requests[0] =
            wl_message("set_selection".ptr, "?ou".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 5);
        zwp_primary_selection_device_v1_requests[1] =
            wl_message("destroy".ptr, "".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);

        zwp_primary_selection_device_v1_events[0] =
            wl_message("data_offer".ptr, "n".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 7);
        zwp_primary_selection_device_v1_events[1] =
            wl_message("selection".ptr, "?o".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 8);

        zwp_primary_selection_device_v1_interface = wl_interface(
            "zwp_primary_selection_device_v1".ptr, 1,
            2, zwp_primary_selection_device_v1_requests.ptr,
            2, zwp_primary_selection_device_v1_events.ptr);

        zwp_primary_selection_offer_v1_requests[0] =
            wl_message("receive".ptr, "sh".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);
        zwp_primary_selection_offer_v1_requests[1] =
            wl_message("destroy".ptr, "".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);

        zwp_primary_selection_offer_v1_events[0] =
            wl_message("offer".ptr, "s".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);

        zwp_primary_selection_offer_v1_interface = wl_interface(
            "zwp_primary_selection_offer_v1".ptr, 1,
            2, zwp_primary_selection_offer_v1_requests.ptr,
            1, zwp_primary_selection_offer_v1_events.ptr);

        zwp_primary_selection_source_v1_requests[0] =
            wl_message("offer".ptr, "s".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);
        zwp_primary_selection_source_v1_requests[1] =
            wl_message("destroy".ptr, "".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);

        zwp_primary_selection_source_v1_events[0] =
            wl_message("send".ptr, "sh".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);
        zwp_primary_selection_source_v1_events[1] =
            wl_message("cancelled".ptr, "".ptr,
                wp_primary_selection_unstable_v1_types.ptr + 0);

        zwp_primary_selection_source_v1_interface = wl_interface(
            "zwp_primary_selection_source_v1".ptr, 1,
            2, zwp_primary_selection_source_v1_requests.ptr,
            2, zwp_primary_selection_source_v1_events.ptr);
    }
}
