/+
 +  Protocol copyright:
 +  Copyright © 2015, 2016 Red Hat
 +
 +  Permission is hereby granted, free of charge, to any person obtaining a
 +  copy of this software and associated documentation files (the "Software"),
 +  to deal in the Software without restriction, including without limitation
 +  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 +  and/or sell copies of the Software, and to permit persons to whom the
 +  Software is furnished to do so, subject to the following conditions:
 +
 +  The above copyright notice and this permission notice (including the next
 +  paragraph) shall be included in all copies or substantial portions of the
 +  Software.
 +
 +  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 +  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 +  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 +  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 +  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 +  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 +  DEALINGS IN THE SOFTWARE.
 +/
/+
 +  D bindings copyright:
 +  Copyright © 2015 Rémi Thebault
 +/
/+
 +      File generated by wayland-scanner-d:
 +  /home/eirikr/.dub/packages/wayland-scanner-d/1.0.0/wayland-scanner-d/wayland-scanner-d -i /usr/share/wayland-protocols/unstable/primary-selection/primary-selection-unstable-v1.xml -m pured.platform.wayland.primary_selection.ifaces --client --ifaces --ifaces_priv_mod pured.platform.wayland.primary_selection.priv.ifaces -o /home/eirikr/Github/tilix/pured/platform/wayland/primary_selection/ifaces.d -x pured.platform.wayland.primary_selection.protocol -x wayland.client.core
 +      Do not edit!
 +/
module pured.platform.wayland.primary_selection.ifaces;

import wayland.client.util;
import wayland.client.opaque_types;
import wayland.client.core;

version (Dynamic) {

    private {
        __gshared wl_interface *zwp_primary_selection_device_manager_v1_if_ptr;
        __gshared wl_interface *zwp_primary_selection_device_v1_if_ptr;
        __gshared wl_interface *zwp_primary_selection_offer_v1_if_ptr;
        __gshared wl_interface *zwp_primary_selection_source_v1_if_ptr;
    }

    package {
        import derelict.util.loader;

        class Wp_primary_selection_unstable_v1ClientLoader : SharedLibLoader {
            this (string libName) {
                super(libName);
            }
            protected override void loadSymbols() {
                zwp_primary_selection_device_manager_v1_if_ptr = cast(wl_interface*) loadSymbol("zwp_primary_selection_device_manager_v1_interface");
                zwp_primary_selection_device_v1_if_ptr = cast(wl_interface*) loadSymbol("zwp_primary_selection_device_v1_interface");
                zwp_primary_selection_offer_v1_if_ptr = cast(wl_interface*) loadSymbol("zwp_primary_selection_offer_v1_interface");
                zwp_primary_selection_source_v1_if_ptr = cast(wl_interface*) loadSymbol("zwp_primary_selection_source_v1_interface");
            }
        }
    }

    @property wl_interface *zwp_primary_selection_device_manager_v1_interface() {
        return zwp_primary_selection_device_manager_v1_if_ptr;
    }
    @property wl_interface *zwp_primary_selection_device_v1_interface() {
        return zwp_primary_selection_device_v1_if_ptr;
    }
    @property wl_interface *zwp_primary_selection_offer_v1_interface() {
        return zwp_primary_selection_offer_v1_if_ptr;
    }
    @property wl_interface *zwp_primary_selection_source_v1_interface() {
        return zwp_primary_selection_source_v1_if_ptr;
    }

}
else {

    import priv = pured.platform.wayland.primary_selection.priv.ifaces;

    @property wl_interface *zwp_primary_selection_device_manager_v1_interface() {
        return &priv.zwp_primary_selection_device_manager_v1_interface;
    }
    @property wl_interface *zwp_primary_selection_device_v1_interface() {
        return &priv.zwp_primary_selection_device_v1_interface;
    }
    @property wl_interface *zwp_primary_selection_offer_v1_interface() {
        return &priv.zwp_primary_selection_offer_v1_interface;
    }
    @property wl_interface *zwp_primary_selection_source_v1_interface() {
        return &priv.zwp_primary_selection_source_v1_interface;
    }

}
