/+
 +  Protocol copyright:
 +  Copyright © 2015, 2016 Red Hat
 +
 +  Permission is hereby granted, free of charge, to any person obtaining a
 +  copy of this software and associated documentation files (the "Software"),
 +  to deal in the Software without restriction, including without limitation
 +  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 +  and/or sell copies of the Software, and to permit persons to whom the
 +  Software is furnished to do so, subject to the following conditions:
 +
 +  The above copyright notice and this permission notice (including the next
 +  paragraph) shall be included in all copies or substantial portions of the
 +  Software.
 +
 +  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 +  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 +  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 +  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 +  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 +  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 +  DEALINGS IN THE SOFTWARE.
 +/
/+
 +  D bindings copyright:
 +  Copyright © 2015 Rémi Thebault
 +/
/+
 +      File generated by wayland-scanner-d:
 +  /home/eirikr/.dub/packages/wayland-scanner-d/1.0.0/wayland-scanner-d/wayland-scanner-d -i /usr/share/wayland-protocols/unstable/primary-selection/primary-selection-unstable-v1.xml -m pured.platform.wayland.primary_selection.protocol --client --protocol -o /home/eirikr/Github/tilix/pured/platform/wayland/primary_selection/protocol.d -x wayland.client.core -x wayland.client.ifaces
 +      Do not edit!
 +/
module pured.platform.wayland.primary_selection.protocol;

import wayland.client.util;
import wayland.client.opaque_types;
import wayland.client.core;
import wayland.client.ifaces;
import wayland.client.protocol;
import pured.platform.wayland.primary_selection.ifaces;

extern (C) {

    struct zwp_primary_selection_device_manager_v1;
    struct zwp_primary_selection_device_v1;
    struct zwp_primary_selection_offer_v1;
    struct zwp_primary_selection_source_v1;

    enum uint ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_CREATE_SOURCE = 0;
    enum uint ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_GET_DEVICE = 1;
    enum uint ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_DESTROY = 2;

    extern (D) void
    zwp_primary_selection_device_manager_v1_set_user_data(zwp_primary_selection_device_manager_v1 *zwp_primary_selection_device_manager_v1, void *user_data)
    {
        wl_proxy_set_user_data(cast(wl_proxy*) zwp_primary_selection_device_manager_v1, user_data);
    }

    extern (D) void *
    zwp_primary_selection_device_manager_v1_get_user_data(zwp_primary_selection_device_manager_v1 *zwp_primary_selection_device_manager_v1)
    {
        return wl_proxy_get_user_data(cast(wl_proxy*) zwp_primary_selection_device_manager_v1);
    }

    /++
     +  create a new primary selection source
     +
     +  Create a new primary selection source.
     +/
    extern (D) zwp_primary_selection_source_v1 *
    zwp_primary_selection_device_manager_v1_create_source(zwp_primary_selection_device_manager_v1 *zwp_primary_selection_device_manager_v1_)
    {
        wl_proxy *id;

        id = wl_proxy_marshal_constructor(
                cast(wl_proxy*) zwp_primary_selection_device_manager_v1_,
                ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_CREATE_SOURCE, zwp_primary_selection_source_v1_interface, null);

        return cast(zwp_primary_selection_source_v1 *) id;
    }

    /++
     +  create a new primary selection device
     +
     +  Create a new data device for a given seat.
     +/
    extern (D) zwp_primary_selection_device_v1 *
    zwp_primary_selection_device_manager_v1_get_device(zwp_primary_selection_device_manager_v1 *zwp_primary_selection_device_manager_v1_, wl_seat *seat)
    {
        wl_proxy *id;

        id = wl_proxy_marshal_constructor(
                cast(wl_proxy*) zwp_primary_selection_device_manager_v1_,
                ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_GET_DEVICE, zwp_primary_selection_device_v1_interface, null, seat);

        return cast(zwp_primary_selection_device_v1 *) id;
    }

    /++
     +  destroy the primary selection device manager
     +
     +  Destroy the primary selection device manager.
     +/
    extern (D) void
    zwp_primary_selection_device_manager_v1_destroy(zwp_primary_selection_device_manager_v1 *zwp_primary_selection_device_manager_v1_)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_device_manager_v1_,
                ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_DESTROY);

        wl_proxy_destroy(cast(wl_proxy*) zwp_primary_selection_device_manager_v1_);
    }

    /++
     +  set the primary selection
     +
     +  Replaces the current selection. The previous owner of the primary
     +  selection will receive a wp_primary_selection_source.cancelled event.
     +
     +  To unset the selection, set the source to NULL.
     +/
    struct zwp_primary_selection_device_v1_listener
    {
        /++
         +  introduce a new wp_primary_selection_offer
         +
         +  Introduces a new wp_primary_selection_offer object that may be used
         +  to receive the current primary selection. Immediately following this
         +  event, the new wp_primary_selection_offer object will send
         +  wp_primary_selection_offer.offer events to describe the offered mime
         +  types.
         +/
        void function (void *data,
                       zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1,
                       zwp_primary_selection_offer_v1 *offer) data_offer;
        /++
         +  advertise a new primary selection
         +
         +  The wp_primary_selection_device.selection event is sent to notify the
         +  client of a new primary selection. This event is sent after the
         +  wp_primary_selection.data_offer event introducing this object, and after
         +  the offer has announced its mimetypes through
         +  wp_primary_selection_offer.offer.
         +
         +  The data_offer is valid until a new offer or NULL is received
         +  or until the client loses keyboard focus. The client must destroy the
         +  previous selection data_offer, if any, upon receiving this event.
         +/
        void function (void *data,
                       zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1,
                       zwp_primary_selection_offer_v1 *id) selection;
    }

    extern (D) int
    zwp_primary_selection_device_v1_add_listener(zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1,
                    const(zwp_primary_selection_device_v1_listener) *listener, void *data)
    {
        alias Callback = extern (C) void function();

        return wl_proxy_add_listener(
                cast(wl_proxy*)zwp_primary_selection_device_v1,
                cast(Callback*)listener, data);
    }

    enum uint ZWP_PRIMARY_SELECTION_DEVICE_V1_SET_SELECTION = 0;
    enum uint ZWP_PRIMARY_SELECTION_DEVICE_V1_DESTROY = 1;

    extern (D) void
    zwp_primary_selection_device_v1_set_user_data(zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1, void *user_data)
    {
        wl_proxy_set_user_data(cast(wl_proxy*) zwp_primary_selection_device_v1, user_data);
    }

    extern (D) void *
    zwp_primary_selection_device_v1_get_user_data(zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1)
    {
        return wl_proxy_get_user_data(cast(wl_proxy*) zwp_primary_selection_device_v1);
    }

    /++
     +  set the primary selection
     +
     +  Replaces the current selection. The previous owner of the primary
     +  selection will receive a wp_primary_selection_source.cancelled event.
     +
     +  To unset the selection, set the source to NULL.
     +/
    extern (D) void
    zwp_primary_selection_device_v1_set_selection(zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1_, zwp_primary_selection_source_v1 *source, uint serial)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_device_v1_,
                ZWP_PRIMARY_SELECTION_DEVICE_V1_SET_SELECTION, source, serial);
    }

    /++
     +  destroy the primary selection device
     +
     +  Destroy the primary selection device.
     +/
    extern (D) void
    zwp_primary_selection_device_v1_destroy(zwp_primary_selection_device_v1 *zwp_primary_selection_device_v1_)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_device_v1_,
                ZWP_PRIMARY_SELECTION_DEVICE_V1_DESTROY);

        wl_proxy_destroy(cast(wl_proxy*) zwp_primary_selection_device_v1_);
    }

    /++
     +  offer to transfer primary selection contents
     +
     +  A wp_primary_selection_offer represents an offer to transfer the contents
     +  of the primary selection clipboard to the client. Similar to
     +  wl_data_offer, the offer also describes the mime types that the data can
     +  be converted to and provides the mechanisms for transferring the data
     +  directly to the client.
     +/
    struct zwp_primary_selection_offer_v1_listener
    {
        /++
         +  advertise offered mime type
         +
         +  Sent immediately after creating announcing the
         +  wp_primary_selection_offer through
         +  wp_primary_selection_device.data_offer. One event is sent per offered
         +  mime type.
         +/
        void function (void *data,
                       zwp_primary_selection_offer_v1 *zwp_primary_selection_offer_v1,
                       const(char) *mime_type) offer;
    }

    extern (D) int
    zwp_primary_selection_offer_v1_add_listener(zwp_primary_selection_offer_v1 *zwp_primary_selection_offer_v1,
                    const(zwp_primary_selection_offer_v1_listener) *listener, void *data)
    {
        alias Callback = extern (C) void function();

        return wl_proxy_add_listener(
                cast(wl_proxy*)zwp_primary_selection_offer_v1,
                cast(Callback*)listener, data);
    }

    enum uint ZWP_PRIMARY_SELECTION_OFFER_V1_RECEIVE = 0;
    enum uint ZWP_PRIMARY_SELECTION_OFFER_V1_DESTROY = 1;

    extern (D) void
    zwp_primary_selection_offer_v1_set_user_data(zwp_primary_selection_offer_v1 *zwp_primary_selection_offer_v1, void *user_data)
    {
        wl_proxy_set_user_data(cast(wl_proxy*) zwp_primary_selection_offer_v1, user_data);
    }

    extern (D) void *
    zwp_primary_selection_offer_v1_get_user_data(zwp_primary_selection_offer_v1 *zwp_primary_selection_offer_v1)
    {
        return wl_proxy_get_user_data(cast(wl_proxy*) zwp_primary_selection_offer_v1);
    }

    /++
     +  request that the data is transferred
     +
     +  To transfer the contents of the primary selection clipboard, the client
     +  issues this request and indicates the mime type that it wants to
     +  receive. The transfer happens through the passed file descriptor
     +  (typically created with the pipe system call). The source client writes
     +  the data in the mime type representation requested and then closes the
     +  file descriptor.
     +
     +  The receiving client reads from the read end of the pipe until EOF and
     +  closes its end, at which point the transfer is complete.
     +/
    extern (D) void
    zwp_primary_selection_offer_v1_receive(zwp_primary_selection_offer_v1 *zwp_primary_selection_offer_v1_, const(char) *mime_type, int fd)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_offer_v1_,
                ZWP_PRIMARY_SELECTION_OFFER_V1_RECEIVE, mime_type, fd);
    }

    /++
     +  destroy the primary selection offer
     +
     +  Destroy the primary selection offer.
     +/
    extern (D) void
    zwp_primary_selection_offer_v1_destroy(zwp_primary_selection_offer_v1 *zwp_primary_selection_offer_v1_)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_offer_v1_,
                ZWP_PRIMARY_SELECTION_OFFER_V1_DESTROY);

        wl_proxy_destroy(cast(wl_proxy*) zwp_primary_selection_offer_v1_);
    }

    /++
     +  offer to replace the contents of the primary selection
     +
     +  The source side of a wp_primary_selection_offer, it provides a way to
     +  describe the offered data and respond to requests to transfer the
     +  requested contents of the primary selection clipboard.
     +/
    struct zwp_primary_selection_source_v1_listener
    {
        /++
         +  send the primary selection contents
         +
         +  Request for the current primary selection contents from the client.
         +  Send the specified mime type over the passed file descriptor, then
         +  close it.
         +/
        void function (void *data,
                       zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1,
                       const(char) *mime_type,
                       int fd) send;
        /++
         +  request for primary selection contents was canceled
         +
         +  This primary selection source is no longer valid. The client should
         +  clean up and destroy this primary selection source.
         +/
        void function (void *data,
                       zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1) cancelled;
    }

    extern (D) int
    zwp_primary_selection_source_v1_add_listener(zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1,
                    const(zwp_primary_selection_source_v1_listener) *listener, void *data)
    {
        alias Callback = extern (C) void function();

        return wl_proxy_add_listener(
                cast(wl_proxy*)zwp_primary_selection_source_v1,
                cast(Callback*)listener, data);
    }

    enum uint ZWP_PRIMARY_SELECTION_SOURCE_V1_OFFER = 0;
    enum uint ZWP_PRIMARY_SELECTION_SOURCE_V1_DESTROY = 1;

    extern (D) void
    zwp_primary_selection_source_v1_set_user_data(zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1, void *user_data)
    {
        wl_proxy_set_user_data(cast(wl_proxy*) zwp_primary_selection_source_v1, user_data);
    }

    extern (D) void *
    zwp_primary_selection_source_v1_get_user_data(zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1)
    {
        return wl_proxy_get_user_data(cast(wl_proxy*) zwp_primary_selection_source_v1);
    }

    /++
     +  add an offered mime type
     +
     +  This request adds a mime type to the set of mime types advertised to
     +  targets. Can be called several times to offer multiple types.
     +/
    extern (D) void
    zwp_primary_selection_source_v1_offer(zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1_, const(char) *mime_type)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_source_v1_,
                ZWP_PRIMARY_SELECTION_SOURCE_V1_OFFER, mime_type);
    }

    /++
     +  destroy the primary selection source
     +
     +  Destroy the primary selection source.
     +/
    extern (D) void
    zwp_primary_selection_source_v1_destroy(zwp_primary_selection_source_v1 *zwp_primary_selection_source_v1_)
    {
        wl_proxy_marshal(cast(wl_proxy*) zwp_primary_selection_source_v1_,
                ZWP_PRIMARY_SELECTION_SOURCE_V1_DESTROY);

        wl_proxy_destroy(cast(wl_proxy*) zwp_primary_selection_source_v1_);
    }


} // extern (C)
